name: Perform Deployment
on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: [ self-hosted, neptune ]
    env:
      DEPLOYMENT_PATH: ${{ secrets.DEPLOYMENT_PATH }}
      DEPLOYMENT_USER: ${{ secrets.DEPLOYMENT_USER }}

    defaults:
      run:
        working-directory: ${{ env.DEPLOYMENT_PATH }}
        shell: bash

    steps:
      - name: Resolve permission issues with ownership
        run: chown -R ${{ env.DEPLOYMENT_USER }}:${{ env.DEPLOYMENT_USER }} .
      - name: Pull latest repo commits
        run: git reset --hard && gh repo sync --force
      - name: Resolve permission issues with ownership
        run: chown -R ${{ env.DEPLOYMENT_USER }}:${{ env.DEPLOYMENT_USER }} .
      - name: Perform updates
        run: sudo su -l ${{ env.DEPLOYMENT_USER }} -c 'cd ${{env.DEPLOYMENT_PATH}} && composer install && composer dump-autoload -o && npm install && npm run build && php artisan migrate --force'
      - name: Resolve permission issues with ownership
        run: |
          chown -R ${{ env.DEPLOYMENT_USER }}:${{ env.DEPLOYMENT_USER }} .
